# Generated by Django 2.2 on 2019-06-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=140)),
                ('price', models.IntegerField()),
                ('author', models.TextField(max_length=200)),
            ],
        ),
    ]
