# Generated by Django 2.0 on 2018-05-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
