# Generated by Django 4.2.5 on 2024-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpolyeeRecord',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('employee_salary', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Employee Record',
                'verbose_name_plural': 'Employees Record',
            },
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student Detail', 'verbose_name_plural': 'Student Details'},
        ),
    ]
