# Generated by Django 3.2.4 on 2021-07-01 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
