# Generated by Django 2.2 on 2019-07-08 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('SerialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateField(default=django.utils.timezone.now)),
                ('Author', models.TextField(max_length=30)),
                ('Designation', models.TextField(max_length=30)),
                ('Subject', models.TextField(max_length=100)),
                ('ReportedTo', models.TextField(max_length=30)),
                ('InstructedBy', models.TextField(max_length=50)),
            ],
        ),
    ]
