# Generated by Django 2.2 on 2019-07-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbook',
            old_name='createdAt',
            new_name='CreatedAt',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='InstructedBy',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='ReportedTo',
        ),
        migrations.AlterField(
            model_name='logbook',
            name='Subject',
            field=models.TextField(max_length=300),
        ),
    ]
