# Generated by Django 2.2 on 2019-07-08 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20190708_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='InstructedBy',
            field=models.TextField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logbook',
            name='ReportedTo',
            field=models.TextField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
