# Generated by Django 2.2 on 2019-07-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20190708_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='InstructedBy',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='ReportedTo',
        ),
    ]
