# Generated by Django 2.2 on 2019-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_auto_20190708_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='Instructor',
            field=models.TextField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='logbook',
            name='Reported',
            field=models.TextField(default=None, max_length=40),
        ),
    ]
