# Generated by Django 2.2 on 2019-07-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_auto_20190708_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='Instructor',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='Reported',
        ),
    ]
