# Generated by Django 2.2 on 2019-07-21 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('SerialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('HDShift', models.TextField(max_length=20)),
                ('CallFrom', models.TextField(max_length=50)),
                ('ProblemType', models.TextField(max_length=100)),
                ('CnctPerson', models.TextField(max_length=30)),
                ('SolvedStatus', models.TextField(max_length=10)),
                ('Remarks', models.TextField(max_length=200)),
            ],
        ),
    ]
