# Generated by Django 2.2 on 2019-07-02 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('SerialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedAt', models.DateField(default=django.utils.timezone.now)),
                ('Author', models.TextField(max_length=100)),
                ('Subject', models.TextField(max_length=300)),
            ],
        ),
    ]
