# Generated by Django 2.2.6 on 2020-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(default='Name', max_length=30)),
                ('CreationTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
