# Generated by Django 2.2 on 2019-06-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
