# Generated by Django 2.2 on 2019-07-14 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('SerialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedAt', models.DateField(default=django.utils.timezone.now)),
                ('ipaddress', models.TextField(max_length=40)),
                ('hdd', models.TextField(max_length=10)),
                ('ram', models.TextField(max_length=20)),
                ('core', models.TextField(max_length=10)),
                ('allocatedfor', models.TextField(max_length=100)),
                ('creationorder', models.TextField(max_length=100)),
                ('os', models.TextField(max_length=40)),
                ('License', models.TextField(max_length=50)),
            ],
        ),
    ]
